apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    email: e.crippa10@studenti.unibg.it  # 🔁 Sostituisci con il tuo indirizzo
    server: https://acme-v02.api.letsencrypt.org/directory  # Produzione
    privateKeySecretRef:
      name: letsencrypt-cluster-key
    solvers:
      - http01:
          ingress:
            class: nginx
