apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
  namespace: keycloak
spec:
  secretName: keycloak-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: keycloak.local
  dnsNames:
    - keycloak.local
  usages:
    - digital signature
    - key encipherment
  renewBefore: 240h
