apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert
  namespace: keycloak
spec:
  secretName: keycloak-tls
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
  commonName: keycloak.local
  dnsNames:
    - keycloak.local
  duration: 2160h  # 90 giorni
  renewBefore: 360h  # 15 giorni
