apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-api-tls
  namespace: minio-tenant
spec:
  secretName: minio-api-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
  commonName: minio.local
  dnsNames:
    - minio.local
