opa:
  image:
    repository: openpolicyagent/opa
    tag: latest

  enable: true

  service:
    enabled: true
    name: opa
    type: ClusterIP
    port: 443

  tls:
    enabled: true
    certFile: /certs/tls.crt
    keyFile: /certs/tls.key

  extraVolumeMounts:
    - name: opa-tls
      mountPath: /certs
      readOnly: true

  extraVolumes:
    - name: opa-tls
      secret:
        secretName: opa-server-tls

  extraArgs:
    - "--tls-cert-file=/certs/tls.crt"
    - "--tls-private-key-file=/certs/tls.key"
    - "--log-level=info"

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Cambia se usi un altro issuer
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - host: opa.mydomain.example  # Cambia con il tuo dominio
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - opa.mydomain.example
        secretName: opa-ingress-tls  # gestito da cert-manager

kubeMgmt:
  enabled: true
  image:
    repository: openpolicyagent/kube-mgmt
    tag: latest
  sync:
    configMaps: true
    secrets: false
    namespaces: []
  replicaCount: 1
