opa:
  image:
      repository: openpolicyagent/opa
      tag: latest
  enable: true
  service:
    enabled: true
    name: opa
    type: ClusterIP
    port: 443

  tls:
    enabled: true
    certFile: /certs/tls.crt
    keyFile: /certs/tls.key

  extraVolumeMounts:
    - name: opa-tls
      mountPath: /certs
      readOnly: true

  extraVolumes:
    - name: opa-tls
      secret:
        secretName: opa-server-tls

  extraArgs:
    - "--tls-cert-file=/certs/tls.crt"
    - "--tls-private-key-file=/certs/tls.key"
    - "--log-level=info"

kubeMgmt:
  enabled: true
  sync:
    configMaps: true
    secrets: false
