# File values.yaml

keycloak:
  replicas: 1
  auth:
    adminUser: admin
    adminPassword: adminpassword  # Cambia questa password in modo sicuro

  # Usa la modalità standalone senza database esterno
  externalDatabase:
    enabled: false

  # Abilitazione del supporto per l'Ingress
  ingress:
    enabled: true
    hostname: "keycloak.local"
    ingressClassName: "nginx"
    tls:
      - secretName: keycloak-tls
        hosts:
          - keycloak.local

  # Configurazione della persistenza (opzionale, ma consigliata per la produzione)
  persistence:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce

  # Configurazione delle risorse (CPU e RAM)
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

  # Opzioni per il supporto HTTPS (configurato tramite cert-manager)
  service:
    type: ClusterIP
    port: 8080
    httpsPort: 8443
