# kube-scheduler-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-scheduler-rolebinding
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: kube-scheduler
    namespace: kube-system
roleRef:
  kind: Role
  name: kube-scheduler-role
  apiGroup: rbac.authorization.k8s.io
