USER-SUPPLIED VALUES:
ingress:
  api:
    enabled: false
  console:
    enabled: false
tenant:
  additionalVolumeMounts: []
  additionalVolumes: []
  buckets:
  - name: referti-clinica
  - name: documenti-transazioni
  certificate:
    certConfig: {}
    externalCaCertSecret: []
    externalCertSecret: []
    requestAutoCert: true
  configSecret:
    accessKey: minio
    name: myminio-env-configuration
    secretKey: minio123
  configuration:
    name: myminio-env-configuration
  env: []
  exposeServices: {}
  features:
    bucketDNS: false
    domains: {}
    enableSFTP: false
  image:
    pullPolicy: IfNotPresent
    repository: quay.io/minio/minio
    tag: RELEASE.2025-04-03T14-56-28Z
  imagePullSecret: {}
  initContainers: []
  lifecycle: {}
  liveness: {}
  logging: {}
  metrics:
    enabled: true
    port: 9000
    protocol: http
  mountPath: /export
  name: myminio-tenant
  podManagementPolicy: Parallel
  pools:
  - affinity: {}
    annotations: {}
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    labels: {}
    name: pool-0
    nodeSelector: {}
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    servers: 1
    size: 10Gi
    storageAnnotations: {}
    storageClassName: standard
    storageLabels: {}
    tolerations: []
    topologySpreadConstraints: []
    volumesPerServer: 1
  poolsMetadata:
    annotations: {}
    labels: {}
  priorityClassName: ""
  prometheusOperator: false
  readiness: {}
  scheduler: {}
  serviceAccountName: ""
  serviceMetadata: {}
  startup: {}
  subPath: /data
  users: []
