apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  annotations:
    meta.helm.sh/release-name: myminio-tenant
    meta.helm.sh/release-namespace: minio-tenant
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  creationTimestamp: "2025-04-06T14:59:58Z"
  generation: 1
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
  name: myminio-tenant
  namespace: minio-tenant
  resourceVersion: "6972"
  uid: d958af4f-c392-485c-9fdf-58e4fe311b04
spec:
  buckets:
  - name: referti-clinica
  - name: documenti-transazioni
  configuration:
    name: myminio-env-configuration
  features:
    bucketDNS: false
    enableSFTP: false
  image: quay.io/minio/minio:RELEASE.2025-04-03T14-56-28Z
  imagePullPolicy: IfNotPresent
  mountPath: /export
  podManagementPolicy: Parallel
  pools:
  - containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    name: pool-0
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    servers: 1
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
    volumesPerServer: 1
  poolsMetadata:
    annotations: {}
    labels: {}
  prometheusOperator: false
  requestAutoCert: true
  subPath: /data
status:
  availableReplicas: 1
  certificates:
    autoCertEnabled: true
    customCertificates: {}
  currentState: Initialized
  drivesOnline: 1
  healthStatus: green
  pools:
  - legacySecurityContext: false
    ssName: myminio-tenant-pool-0
    state: PoolInitialized
  provisionedBuckets: true
  revision: 0
  syncVersion: v6.0.0
  usage:
    capacity: 1018725621760
    rawCapacity: 1018725621760
    rawUsage: 7383199744
    usage: 7383199744
  writeQuorum: 1
