# minio-tenant-minio-certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tenant-certmanager-cert
  namespace: minio-tenant
spec:
  dnsNames:
    - "minio.minio-tenant"
    - "minio.minio-tenant.svc"
    - 'minio.minio-tenant.svc.cluster.local'
    - '*.minio.minio-tenant.svc.cluster.local'
    - '*.minio-hl.minio-tenant.svc.cluster.local'
    - '*.minio.minio.minio-tenant.svc.cluster.local'
    - "minio-api.local"
    - "minio-console.local"
  secretName: minio-tls
  issuerRef:
    name: tenant-ca-issuer