apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: my-org.com  # The bundle name will also be used for the target
spec:
  sources:
  # Include a bundle of publicly trusted certificates which can be
  # used to validate most TLS certificates on the internet, such as
  # those issued by Let's Encrypt, Google, Amazon and others.
  # NB: Unless you pin the package providing these CAs, the default can change!
  - useDefaultCAs: true

  # One more Secret source, this time including all certificates from every key
#  - secret:
#      name: "operator-ca-tls"
#      key: "ca.crt"
  - secret:
      name: "keycloak-ca-tls"
      key: "ca.crt"
  - secret:
      name: "tenant-1-ca-tls"
      key: "ca.crt"

  target:
    # Sync the bundle to a ConfigMap called `my-org.com` in every namespace which
    # has the label "linkerd.io/inject=enabled"
    # All ConfigMaps will include a PEM-formatted bundle, here named "root-certs.pem"
    # and in this case we also request binary formatted bundles in JKS and PKCS#12 formats,
    # here named "bundle.jks" and "bundle.p12".
    configMap:
      key: "ca-certificates.crt"
    secret: 
      key: "ca-certificates.crt"
    additionalFormats:
      jks:
        key: "ca-certificates.jks"
      pkcs12:
        key: "ca-certificates.p12"
    namespaceSelector:
      matchLabels:
        create-ca-bundle: "true"