apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-03-24T07:56:14Z"
    generateName: minio-operator-75bbc5d4dc-
    labels:
      app.kubernetes.io/instance: operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: operator
      app.kubernetes.io/version: v7.0.1
      helm.sh/chart: operator-7.0.1
      pod-template-hash: 75bbc5d4dc
    name: minio-operator-75bbc5d4dc-bwbgv
    namespace: minio-operator
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: minio-operator-75bbc5d4dc
      uid: 3df81df6-ad7a-4967-aa2f-fd974d13f2e0
    resourceVersion: "10332"
    uid: ea56c2a0-c3b4-4a57-8d95-cf1bf1ec568b
  spec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: name
              operator: In
              values:
              - minio-operator
          topologyKey: kubernetes.io/hostname
    containers:
    - args:
      - controller
      env:
      - name: OPERATOR_STS_ENABLED
        value: "on"
      image: quay.io/minio/operator:v7.0.1
      imagePullPolicy: IfNotPresent
      name: operator
      resources:
        requests:
          cpu: 200m
          ephemeral-storage: 500Mi
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-vl25n
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: minikube
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccount: minio-operator
    serviceAccountName: minio-operator
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-vl25n
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-03-24T14:32:14Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-03-24T07:56:14Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-03-24T14:32:14Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-03-24T14:32:14Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-03-24T07:56:14Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://00c406bdc8249ce48a4fad75aa98fc10ae7db263085e1ad33b2d42bb4252014d
      image: quay.io/minio/operator:v7.0.1
      imageID: docker-pullable://quay.io/minio/operator@sha256:e5d98b0a1e91d8325002c09e45fd5d0d0a72e7e756e990250d90e178cccf0d49
      lastState:
        terminated:
          containerID: docker://41bf7cd83e2e5fec44b0a98e9e23fb0fe1a4f8d4f2440b20e20a503ada69bfa9
          exitCode: 255
          finishedAt: "2025-03-24T14:31:44Z"
          reason: Error
          startedAt: "2025-03-24T14:10:34Z"
      name: operator
      ready: true
      restartCount: 3
      started: true
      state:
        running:
          startedAt: "2025-03-24T14:32:10Z"
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-vl25n
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 192.168.49.2
    hostIPs:
    - ip: 192.168.49.2
    phase: Running
    podIP: 10.244.0.25
    podIPs:
    - ip: 10.244.0.25
    qosClass: Burstable
    startTime: "2025-03-24T07:56:14Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2025-03-24T07:56:14Z"
    generateName: minio-operator-75bbc5d4dc-
    labels:
      app.kubernetes.io/instance: operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: operator
      app.kubernetes.io/version: v7.0.1
      helm.sh/chart: operator-7.0.1
      operator: leader
      pod-template-hash: 75bbc5d4dc
    name: minio-operator-75bbc5d4dc-c9ntg
    namespace: minio-operator
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: minio-operator-75bbc5d4dc
      uid: 3df81df6-ad7a-4967-aa2f-fd974d13f2e0
    resourceVersion: "10292"
    uid: 1aafe659-b73c-43ca-9ec2-52d23541b147
  spec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: name
              operator: In
              values:
              - minio-operator
          topologyKey: kubernetes.io/hostname
    containers:
    - args:
      - controller
      env:
      - name: OPERATOR_STS_ENABLED
        value: "on"
      image: quay.io/minio/operator:v7.0.1
      imagePullPolicy: IfNotPresent
      name: operator
      resources:
        requests:
          cpu: 200m
          ephemeral-storage: 500Mi
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-qjzpj
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: minikube
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccount: minio-operator
    serviceAccountName: minio-operator
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-qjzpj
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-03-24T14:32:12Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-03-24T07:56:14Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-03-24T14:32:12Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-03-24T14:32:12Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-03-24T07:56:14Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://60334abbe86e5a64c85164738c077cc2763aee54f773e0ff80a1e679fb8115dd
      image: quay.io/minio/operator:v7.0.1
      imageID: docker-pullable://quay.io/minio/operator@sha256:e5d98b0a1e91d8325002c09e45fd5d0d0a72e7e756e990250d90e178cccf0d49
      lastState:
        terminated:
          containerID: docker://067ee80e19ddc988f82a53b74a2998f234612ffc4bb07b249ae1279d9aca3eb1
          exitCode: 255
          finishedAt: "2025-03-24T14:31:44Z"
          reason: Error
          startedAt: "2025-03-24T14:10:33Z"
      name: operator
      ready: true
      restartCount: 3
      started: true
      state:
        running:
          startedAt: "2025-03-24T14:32:10Z"
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-qjzpj
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 192.168.49.2
    hostIPs:
    - ip: 192.168.49.2
    phase: Running
    podIP: 10.244.0.26
    podIPs:
    - ip: 10.244.0.26
    qosClass: Burstable
    startTime: "2025-03-24T07:56:14Z"
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: operator
      meta.helm.sh/release-namespace: minio-operator
    creationTimestamp: "2025-03-24T07:56:14Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/version: v7.0.1
      helm.sh/chart: operator-7.0.1
    name: operator
    namespace: minio-operator
    resourceVersion: "2513"
    uid: 0cde5e2b-03e6-4ee0-ba11-dd0641ac4a66
  spec:
    clusterIP: 10.107.49.207
    clusterIPs:
    - 10.107.49.207
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 4221
      protocol: TCP
      targetPort: 4221
    selector:
      app.kubernetes.io/instance: operator
      app.kubernetes.io/name: operator
      operator: leader
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: operator
      meta.helm.sh/release-namespace: minio-operator
    creationTimestamp: "2025-03-24T07:56:14Z"
    labels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/version: v7.0.1
      helm.sh/chart: operator-7.0.1
    name: sts
    namespace: minio-operator
    resourceVersion: "2509"
    uid: 15cfbe65-a3fc-4f29-962b-176e627cdda0
  spec:
    clusterIP: 10.100.170.77
    clusterIPs:
    - 10.100.170.77
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 4223
      protocol: TCP
      targetPort: 4223
    selector:
      app.kubernetes.io/instance: operator
      app.kubernetes.io/name: operator
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: operator
      meta.helm.sh/release-namespace: minio-operator
    creationTimestamp: "2025-03-24T07:56:14Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/version: v7.0.1
      helm.sh/chart: operator-7.0.1
    name: minio-operator
    namespace: minio-operator
    resourceVersion: "10337"
    uid: 0cf75423-10c1-40ea-88e0-446feaa8b1bf
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: operator
        app.kubernetes.io/name: operator
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: operator
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: operator
          app.kubernetes.io/version: v7.0.1
          helm.sh/chart: operator-7.0.1
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - minio-operator
              topologyKey: kubernetes.io/hostname
        containers:
        - args:
          - controller
          env:
          - name: OPERATOR_STS_ENABLED
            value: "on"
          image: quay.io/minio/operator:v7.0.1
          imagePullPolicy: IfNotPresent
          name: operator
          resources:
            requests:
              cpu: 200m
              ephemeral-storage: 500Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        serviceAccount: minio-operator
        serviceAccountName: minio-operator
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2025-03-24T07:56:14Z"
      lastUpdateTime: "2025-03-24T07:56:29Z"
      message: ReplicaSet "minio-operator-75bbc5d4dc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-03-24T14:32:14Z"
      lastUpdateTime: "2025-03-24T14:32:14Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "2"
      deployment.kubernetes.io/max-replicas: "3"
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: operator
      meta.helm.sh/release-namespace: minio-operator
    creationTimestamp: "2025-03-24T07:56:14Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: operator
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: operator
      app.kubernetes.io/version: v7.0.1
      helm.sh/chart: operator-7.0.1
      pod-template-hash: 75bbc5d4dc
    name: minio-operator-75bbc5d4dc
    namespace: minio-operator
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: minio-operator
      uid: 0cf75423-10c1-40ea-88e0-446feaa8b1bf
    resourceVersion: "10335"
    uid: 3df81df6-ad7a-4967-aa2f-fd974d13f2e0
  spec:
    replicas: 2
    selector:
      matchLabels:
        app.kubernetes.io/instance: operator
        app.kubernetes.io/name: operator
        pod-template-hash: 75bbc5d4dc
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: operator
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: operator
          app.kubernetes.io/version: v7.0.1
          helm.sh/chart: operator-7.0.1
          pod-template-hash: 75bbc5d4dc
      spec:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - minio-operator
              topologyKey: kubernetes.io/hostname
        containers:
        - args:
          - controller
          env:
          - name: OPERATOR_STS_ENABLED
            value: "on"
          image: quay.io/minio/operator:v7.0.1
          imagePullPolicy: IfNotPresent
          name: operator
          resources:
            requests:
              cpu: 200m
              ephemeral-storage: 500Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          fsGroup: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        serviceAccount: minio-operator
        serviceAccountName: minio-operator
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    fullyLabeledReplicas: 2
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
kind: List
metadata:
  resourceVersion: ""
