accessKey: "minioaccesskey"
secretKey: "miniosecretkey"
persistence:
  enabled: true
  size: 10Gi
ingress:
  enabled: true
  hostname: "minio.local"
  path: /
  ingressClassName: "nginx"
  tls:
    - secretName: minio-tls
      hosts:
        - minio.local
