tenant:
  name: minio
  image:
    repository: quay.io/minio/minio
    tag: RELEASE.2025-04-03T14-56-28Z
    pullPolicy: IfNotPresent
  config:
    name: minio-env-configuration
  identity:
    openid:
      enabled: true
      configUrl: https://keycloak.local/realms/minio-sso/.well-known/openid-configuration
      clientId: minio-client
      clientSecret: ""  # Sostituibile con un secret se necessario
      redirectUri: https://minio-console.local/oauth_callback
      claimName: policy
      scopes: openid,profile,email
  pools:
    - name: pool-0
      servers: 1
      volumesPerServer: 1
      size: 10Gi
      storageClassName: standard
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
      containerSecurityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
  mountPath: /export
  subPath: /data
  metrics:
    enabled: true
    port: 9000
    protocol: http
  certificate:
    requestAutoCert: false  # Disabilitato perché usi cert-manager e i tuoi certificati
  buckets:
    - name: referti-clinica
  ingress:
    api:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
      tls:
        - hosts:
            - minio.local
          secretName: minio-api-tls
      host: minio.local
      path: /
      pathType: Prefix
    console:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
      tls:
        - hosts:
            - minio-console.local
          secretName: minio-console-tls
      host: minio-console.local
      path: /
      pathType: Prefix
