apiVersion: v1
kind: Secret
metadata:
  name: minio-user-alice
type: Opaque
stringData:
  CONSOLE_ACCESS_KEY: alice
  CONSOLE_SECRET_KEY: alicePass

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-user-bob
type: Opaque
stringData:
  CONSOLE_ACCESS_KEY: bob
  CONSOLE_SECRET_KEY: bobPass

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-user-carol
type: Opaque
stringData:
  CONSOLE_ACCESS_KEY: carol
  CONSOLE_SECRET_KEY: carolPass
