apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-admin-policy
  namespace: opa
  labels:
    openpolicyagent.org/policy: rego
terms: []
data:
  minio.rego: |
    package minio.authz

    default allow := false

    allow if {
      input.subject.groups[_] == "storage-readers"
      input.action == "read"
      input.resource.type == "object"
    }
  minio_admin_access.rego: |
    package minio.authz

    # Consenti tutte le azioni solo all'utente amministratore "minio"
    allow if {
      input.user == "minio"
    }
