apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-admin-policy
  namespace: opa
  labels:
    openpolicyagent.org/policy: rego
data:
  minio.rego: |
    package minio.authz
    default allow = false

    allow {
      input.subject.groups[_] == "storage-readers"
      input.action == "read"
      input.resource.type == "object"
    }
  terms: |
    # Add your terms here if required by your application
    # Example:
    # - term1
    # - term2
  minio_admin_access.rego: |
    package minio.authz

    default allow = false

    # Consenti tutte le azioni solo all'utente amministratore "minio"
    allow {
      input.user == "minio"
    }
