apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-policy
  namespace: opa
  labels:
    openpolicyagent.org/policy: rego
data:
  minio.rego: |
    package minio.authz
    default allow = false

    allow {
      input.subject.groups[_] == "storage-readers"
      input.action == "read"
      input.resource.type == "object"
    }
